package notification;

public abstract class Message {	
	
	public enum MessageType {
		REQUEST_INFO_TO_DRIVER, 
		VEHICLE_INFO_TO_CUSTOMER,
		VEHICLE_NOT_IMMEDIATELY_AVAILABLE, 
		VEHICLE_WAIT_30_MINUTES, 
		NO_VEHICLE_AVAILBLE,
		RIDE_PAYMENT_SUCCESS_INFO,
		RIDE_PAYMENT_FAILURE_INFO,
		SHUTTLE_NOTIFICATION,
		YEARLY_BILLING_REPORT_TO_CUSTOMER,
		INTERNAL_YEARLY_REVENUE_REPORT
	}
	
	public abstract String createMessage (MessageType msg);
	
}
